# Generated by Django 4.1.4 on 2023-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_advuser_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Товар'),
        ),
    ]
